#!/usr/bin/env python3
"""Pull a RHAISTRAT issue from Jira into the local/ workspace for human review.

Fetches the strategy description, linked RFE context, and review comments.
Only works on post-CI strategies (must have strat-creator-rubric-pass or
strat-creator-needs-attention label).

Usage:
    python3 scripts/pull_strategy.py RHAISTRAT-1520
    python3 scripts/pull_strategy.py RHAISTRAT-1520 --local-dir local

Exit codes:
    0 — success
    1 — issue not found, missing post-CI labels, or API error
    2 — missing JIRA credentials
"""

import argparse
import os
import re
import sys
import tempfile

sys.path.insert(0, os.path.dirname(__file__))

import type_registry
from jira_utils import (
    RFE_REFERENCE_MARKER,
    adf_to_markdown,
    attachment_sort_key,
    download_attachment,
    get_comments,
    get_issue,
    reconstruct_business_need,
    require_env,
)

# The default work type, rfe-strategy: its post-CI labels, review comment prefix, workspace, dirs,
# frontmatter fields, overflow attachment and the relation back to its input. The body contract
# (STRATEGY_HEADING, the attachment notice) stays literal: both types share it. A key of a type
# whose inputs[0].relation.kind is self (initiative-strategy) is its own input: its frontmatter
# fields and Business Need heading are its type's (_same_ticket_type).
# For now: labels, comment prefix, workspace, dirs and attachment name stay rfe-strategy's (the self
# type's are equal); resolve per call (type_registry.resolve(ids=[strat_key])) once a type differs.
_TYPES = type_registry.load()
_TYPE = _TYPES.get(type_registry.LEGACY_DEFAULT_TYPE)
_LABELS = _TYPE.labels
_DIRS = _TYPE.dirs("bare")
WORKSPACE = _TYPE.get("workspace.root")
LINK_TYPE = _TYPE.get("inputs.0.relation.link_type")
INPUT_PREFIX = _TYPE.get("inputs.0.jira.key_prefixes.0")
NO_SOURCE_REF = INPUT_PREFIX + "0"  # no linked input; push_strategy.py skips it

POST_CI_LABELS = {_LABELS["rubric_pass"], _LABELS["needs_attention"]}

STRAT_CREATOR_COMMENT_MARKER = _TYPE.get("conventions.comment_prefix")
STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"
STRATEGY_ATTACHMENT_TEMPLATE = _TYPE.get("pipeline.body_overflow.attachment")
ATTACHMENT_NOTICE_MARKER = "exceeds Jira's description size limit"


def _same_ticket_type(key):
    """The type of ``key`` when the ticket is its own input (relation self), else None."""
    desc = _TYPES.detect(key)
    return desc if desc and desc.get("inputs.0.relation.kind") == "self" else None


def _newest_attachment(attachments, filename):
    """Return the newest attachment with ``filename``, if any."""
    candidates = [att for att in attachments
                  if att.get("filename") == filename]
    return (max(candidates, key=attachment_sort_key)
            if candidates else None)


def extract_review_comment(comments):
    """Find the most recent review comment posted by strat-creator.

    Looks for comments containing the [Strat Creator] marker.
    Returns the markdown body of the most recent match, or None.
    """
    matches = []
    for comment in comments:
        body_adf = comment.get("body")
        if not body_adf:
            continue
        body_md = adf_to_markdown(body_adf).strip()
        if STRAT_CREATOR_COMMENT_MARKER in body_md:
            matches.append(body_md)
    return matches[-1] if matches else None


def pull_strategy(server, user, token, strat_key, local_dir=WORKSPACE):
    """Pull a RHAISTRAT issue and its context into the local workspace.

    Returns a dict summarizing what was pulled, or raises SystemExit on error.
    """
    # Fetch the STRAT issue
    issue = get_issue(server, user, token, strat_key,
                      fields=["summary", "description", "labels",
                              "priority", "issuelinks", "attachment"])
    fields = issue.get("fields", {})

    # Validate post-CI labels
    labels = set(fields.get("labels", []))
    if not labels & POST_CI_LABELS:
        print(f"Error: {strat_key} does not have a post-CI label "
              f"({', '.join(sorted(POST_CI_LABELS))}). "
              f"Current labels: {', '.join(sorted(labels)) or '(none)'}",
              file=sys.stderr)
        sys.exit(1)

    summary = fields.get("summary", "Untitled")
    priority_field = fields.get("priority")
    priority = priority_field.get("name", "Major") if priority_field else "Major"
    description_adf = fields.get("description")
    description_md = adf_to_markdown(description_adf).strip() if description_adf else ""

    # A ticket that is its own input: the description is the input's (its
    # owner's), and the strategy is only in the newest attachment.
    same_ticket = _same_ticket_type(strat_key)
    work_type = same_ticket or _TYPE
    if same_ticket:
        heading = same_ticket.get("pipeline.section_ownership.0.heading")
        description_md = f"{heading}\n\n{description_md}"

    # Check for strategy attachment (content limit overflow)
    attachments = fields.get("attachment", [])
    att_filename = STRATEGY_ATTACHMENT_TEMPLATE.format(issue_key=strat_key)
    strategy_attachment = _newest_attachment(attachments, att_filename)

    if strategy_attachment and (same_ticket or
                                ATTACHMENT_NOTICE_MARKER in description_md):
        with tempfile.NamedTemporaryFile(
                mode="wb", suffix=".md", delete=False) as tmp:
            tmp_path = tmp.name
        try:
            download_attachment(server, user, token,
                                strategy_attachment["content"], tmp_path)
            with open(tmp_path, "r", encoding="utf-8") as f:
                full_strategy = f.read().strip()
        finally:
            os.unlink(tmp_path)

        if STRATEGY_HEADING in description_md:
            description_md = re.sub(
                r'## Strategy \(AI Generated by Agentic SDLC Pipeline\)'
                r'.*?(?=\n## (?!#)|$)',
                full_strategy + "\n",
                description_md,
                flags=re.DOTALL,
            )
        else:
            description_md = description_md.rstrip() + "\n\n" + full_strategy

        print(f"  Strategy loaded from attachment: {att_filename}")
    elif strategy_attachment:
        print(f"  Ignoring orphan attachment {att_filename} "
              "(description has full strategy content)")

    # Find linked RFE via Cloners (none for a ticket that is its own input)
    rfe_key = None
    strat_links = [] if same_ticket else fields.get("issuelinks", [])
    for link in strat_links:
        if link.get("type", {}).get("name") != LINK_TYPE:
            continue
        for direction in ("outwardIssue", "inwardIssue"):
            issue_ref = link.get(direction, {})
            key = issue_ref.get("key", "")
            if key.startswith(INPUT_PREFIX):
                rfe_key = key
                break
        if rfe_key:
            break

    result = {"strat_key": strat_key, "files": []}

    # Fetch RFE original (needed before writing strategy file for reconstruction)
    rfe_md = ""
    if rfe_key:
        originals_dir = os.path.join(local_dir, _DIRS["originals"])
        os.makedirs(originals_dir, exist_ok=True)

        rfe_data = get_issue(server, user, token, rfe_key,
                             fields=["description"])
        rfe_desc_adf = rfe_data.get("fields", {}).get("description")
        rfe_md = adf_to_markdown(rfe_desc_adf).strip() if rfe_desc_adf else ""

        rfe_path = os.path.join(originals_dir, f"{rfe_key}.md")
        with open(rfe_path, "w", encoding="utf-8") as f:
            f.write(rfe_md + "\n")
        result["files"].append(rfe_path)
        result["rfe_key"] = rfe_key
        print(f"  RFE original: {rfe_path}")

    # Reconstruct Business Need from linked RFE if description has a reference
    if RFE_REFERENCE_MARKER in description_md and not rfe_key:
        print(f"  WARNING: {strat_key} description contains an RFE reference "
              f"link but no linked RHAIRFE was found via Cloners. "
              f"Business Need will NOT be reconstructed.",
              file=sys.stderr)
    elif RFE_REFERENCE_MARKER in description_md and rfe_key and not rfe_md:
        print(f"  WARNING: {strat_key} linked to {rfe_key} but its Jira "
              f"description is empty. Business Need will NOT be reconstructed.",
              file=sys.stderr)
    description_md = reconstruct_business_need(description_md, rfe_md)

    # Write strategy file
    tasks_dir = os.path.join(local_dir, _DIRS["tasks"])
    os.makedirs(tasks_dir, exist_ok=True)
    strat_path = os.path.join(tasks_dir, f"{strat_key}.md")

    from artifact_utils import write_frontmatter
    frontmatter = {
        work_type.id_field: strat_key,
        "title": summary,
        work_type.get("inputs.0.source_ref_field"):
            strat_key if same_ticket else rfe_key or NO_SOURCE_REF,
        work_type.tracker_key_field: strat_key,
        "priority": priority,
        "status": "Refined",
        "workflow": "local",
        "type": work_type.name,
    }
    write_frontmatter(strat_path, frontmatter, "strat-task")

    # Append body content
    with open(strat_path, "a", encoding="utf-8") as f:
        f.write(f"\n{description_md}\n")
    result["files"].append(strat_path)
    print(f"  Strategy: {strat_path}")

    # Fetch RFE comments
    if rfe_key:
        rfe_comments = get_comments(server, user, token, rfe_key)
        if rfe_comments:
            comments_path = os.path.join(originals_dir, f"{rfe_key}-comments.md")
            with open(comments_path, "w", encoding="utf-8") as f:
                f.write(f"# Comments: {rfe_key}\n\n")
                for comment in rfe_comments:
                    author = (comment.get("author", {}).get("displayName")
                              or "Unknown")
                    created = comment.get("created", "")[:10]
                    body_adf = comment.get("body")
                    body_md = adf_to_markdown(body_adf).strip() if body_adf else ""
                    f.write(f"## {author} — {created}\n\n{body_md}\n\n")
            result["files"].append(comments_path)
            print(f"  RFE comments: {comments_path}")

    # Fetch review summary from comments
    reviews_dir = os.path.join(local_dir, _DIRS["reviews"])
    strat_comments = get_comments(server, user, token, strat_key)
    review_md = extract_review_comment(strat_comments)
    if review_md:
        os.makedirs(reviews_dir, exist_ok=True)
        summary_path = os.path.join(reviews_dir, f"{strat_key}-review-summary.md")
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write(review_md + "\n")
        result["files"].append(summary_path)
        print(f"  Review summary: {summary_path}")

    # Fetch full review from attachment
    attachments = fields.get("attachment", [])
    review_attachment = _newest_attachment(
        attachments, f"{strat_key}-review.md")
    if review_attachment:
        os.makedirs(reviews_dir, exist_ok=True)
        full_path = os.path.join(reviews_dir, f"{strat_key}-review.md")
        download_attachment(server, user, token,
                            review_attachment["content"], full_path)
        result["files"].append(full_path)
        print(f"  Full review: {full_path}")

    has_rubric_pass = _LABELS["rubric_pass"] in labels
    result["has_rubric_pass"] = has_rubric_pass
    result["has_needs_attention"] = _LABELS["needs_attention"] in labels

    return result


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    # For now: kept literal for byte-identical rfe-strategy output; reword when the Initiative job goes live
    parser.add_argument("strat_key", help="RHAISTRAT issue key")
    parser.add_argument("--local-dir", default=WORKSPACE,
                        help="Local workspace directory (default: local)")
    args = parser.parse_args()

    if not (args.strat_key.startswith(_TYPE.write_prefix)
            or _same_ticket_type(args.strat_key)):
        # For now: kept literal for byte-identical rfe-strategy output; reword when the Initiative job goes live
        print(f"Error: expected RHAISTRAT-NNNN key, got '{args.strat_key}'",
              file=sys.stderr)
        sys.exit(1)

    server, user, token = require_env()
    if not all([server, user, token]):
        print("Error: JIRA_SERVER, JIRA_USER, and JIRA_TOKEN required.",
              file=sys.stderr)
        sys.exit(2)

    print(f"Pulling {args.strat_key} into {args.local_dir}/...")
    result = pull_strategy(server, user, token, args.strat_key, args.local_dir)

    print(f"\nPulled {len(result['files'])} files.")
    if result.get("has_rubric_pass"):
        print("Status: CI-approved (rubric-pass). Use /strategy-signoff when ready.")
    elif result.get("has_needs_attention"):
        print("Status: Needs attention. Use /strategy-push to resubmit after fixing.")


if __name__ == "__main__":
    main()
